using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LiteBus.SourceGenerator;

/// <summary>
///     Roslyn incremental source generator that discovers all LiteBus handler types in the compilation
///     and emits an AOT-safe <c>GeneratedLiteBusHandlers</c> class. This class replaces the
///     reflection-based <c>RegisterFromAssembly</c> with a statically-known list of <c>typeof(…)</c>
///     references that survive IL trimming and Native AOT publishing.
///     <para>
///         Open generic handlers (e.g. <c>class Validator&lt;T&gt; : ICommandPreHandler&lt;T&gt;</c>)
///         are automatically closed against every matching concrete message type discovered in the
///         same compilation, so the source-generated list contains
///         <c>typeof(Validator&lt;CreateOrderCommand&gt;)</c> etc. rather than requiring the runtime
///         to call <c>MakeGenericType</c>.
///     </para>
/// </summary>
[Generator]
public sealed class LiteBusHandlersGenerator : IIncrementalGenerator
{
    // -----------------------------------------------------------------------
    // Marker interface names recognised by the generator
    // -----------------------------------------------------------------------

    private static readonly string[] CommandMarkerNames =
    [
        "LiteBus.Commands.Abstractions.IRegistrableCommandConstruct"
    ];

    private static readonly string[] EventMarkerNames =
    [
        "LiteBus.Events.Abstractions.IRegistrableEventConstruct"
    ];

    private static readonly string[] QueryMarkerNames =
    [
        "LiteBus.Queries.Abstractions.IRegistrableQueryConstruct"
    ];

    // -----------------------------------------------------------------------
    // IIncrementalGenerator implementation
    // -----------------------------------------------------------------------

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Collect();

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations);

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) =>
        {
            var (compilation, classes) = source;
            Execute(compilation, classes, spc);
        });
    }

    // -----------------------------------------------------------------------
    // Core logic
    // -----------------------------------------------------------------------

    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classes,
        SourceProductionContext context)
    {
        var commandMarkers = ResolveSymbols(compilation, CommandMarkerNames);
        var eventMarkers   = ResolveSymbols(compilation, EventMarkerNames);
        var queryMarkers   = ResolveSymbols(compilation, QueryMarkerNames);

        if (commandMarkers.Length == 0 && eventMarkers.Length == 0 && queryMarkers.Length == 0)
        {
            var emptySource = "// <auto-generated/>\n// LiteBus.SourceGenerator: no LiteBus abstractions found in compilation.\n";
            context.AddSource("GeneratedLiteBusHandlers.g.cs", SourceText.From(emptySource, Encoding.UTF8));
            return;
        }

        // Buckets for concrete (non-generic) types
        var commandHandlers = new List<INamedTypeSymbol>();
        var eventHandlers   = new List<INamedTypeSymbol>();
        var queryHandlers   = new List<INamedTypeSymbol>();

        // Buckets for open-generic handler types (e.g. Validator<T> : ICommandPreHandler<T>)
        var openGenericCommandHandlers = new List<INamedTypeSymbol>();
        var openGenericEventHandlers   = new List<INamedTypeSymbol>();
        var openGenericQueryHandlers   = new List<INamedTypeSymbol>();

        foreach (var classDecl in classes)
        {
            var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol typeSymbol)
                continue;

            if (typeSymbol.IsAbstract || typeSymbol.TypeKind != TypeKind.Class)
                continue;

            if (typeSymbol.TypeParameters.IsEmpty)
            {
                // Concrete non-generic class
                if (ImplementsAny(typeSymbol, commandMarkers))
                    commandHandlers.Add(typeSymbol);
                else if (ImplementsAny(typeSymbol, eventMarkers))
                    eventHandlers.Add(typeSymbol);
                else if (ImplementsAny(typeSymbol, queryMarkers))
                    queryHandlers.Add(typeSymbol);
            }
            else
            {
                // Open-generic class — only include if it is a handler (not a message type)
                if (!IsOpenGenericHandler(typeSymbol))
                    continue;

                if (ImplementsAny(typeSymbol, commandMarkers))
                    openGenericCommandHandlers.Add(typeSymbol);
                else if (ImplementsAny(typeSymbol, eventMarkers))
                    openGenericEventHandlers.Add(typeSymbol);
                else if (ImplementsAny(typeSymbol, queryMarkers))
                    openGenericQueryHandlers.Add(typeSymbol);
            }
        }

        // Close open-generic handlers with every matching concrete message type and add
        // the closed forms to the appropriate bucket so they appear in the generated list.
        CloseAndAdd(openGenericCommandHandlers, commandHandlers);
        CloseAndAdd(openGenericEventHandlers,   eventHandlers);
        CloseAndAdd(openGenericQueryHandlers,   queryHandlers);

        var source = GenerateSource(commandHandlers, eventHandlers, queryHandlers);
        context.AddSource("GeneratedLiteBusHandlers.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    // -----------------------------------------------------------------------
    // Open-generic handler helpers
    // -----------------------------------------------------------------------

    /// <summary>
    ///     Returns <see langword="true"/> when <paramref name="type"/> is an open-generic class
    ///     whose single type parameter appears as the bare message-type argument in at least one
    ///     LiteBus handler interface it implements.  Only single-type-parameter handlers are
    ///     supported (multi-parameter generics are ignored).
    /// </summary>
    private static bool IsOpenGenericHandler(INamedTypeSymbol type)
    {
        // We only handle the common single-type-parameter pattern (e.g. Foo<T>).
        if (type.TypeParameters.Length != 1)
            return false;

        var typeParam = type.TypeParameters[0];

        // Walk the implemented interfaces.  The handler is "open generic" when at least
        // one interface has the class's type parameter as a direct type argument
        // (e.g. ICommandPreHandler<T> where T is typeParam).
        foreach (var iface in type.AllInterfaces)
        {
            foreach (var arg in iface.TypeArguments)
            {
                if (arg is ITypeParameterSymbol tp &&
                    SymbolEqualityComparer.Default.Equals(tp, typeParam))
                    return true;
            }
        }

        return false;
    }

    /// <summary>
    ///     Closes each open-generic handler in <paramref name="openHandlers"/> against every
    ///     candidate in <paramref name="concreteTypes"/> that satisfies the handler's type-
    ///     parameter constraints, and appends the resulting closed types to
    ///     <paramref name="concreteTypes"/>.
    /// </summary>
    private static void CloseAndAdd(
        List<INamedTypeSymbol> openHandlers,
        List<INamedTypeSymbol> concreteTypes)
    {
        if (openHandlers.Count == 0)
            return;

        // Take a snapshot so we don't mutate the list while iterating it.
        var candidates = concreteTypes.ToArray();

        foreach (var openHandler in openHandlers)
        {
            // Only single-type-parameter handlers are supported.
            if (openHandler.TypeParameters.Length != 1)
                continue;

            var typeParam = openHandler.TypeParameters[0];

            foreach (var candidate in candidates)
            {
                if (!SatisfiesConstraints(candidate, typeParam))
                    continue;

                try
                {
                    // Build the closed type, e.g. Validator<CreateOrderCommand>.
                    var closedType = openHandler.Construct(candidate);
                    concreteTypes.Add(closedType);
                }
                catch
                {
                    // Roslyn's Construct() can throw when the combination of type arguments does not
                    // satisfy constraints that are only verifiable at runtime (e.g. struct/unmanaged
                    // constraints resolved via generic substitution).  These edge cases are safe to
                    // skip — the open-generic handler simply won't be emitted for that candidate,
                    // which is the correct behaviour (the same result as a failed MakeGenericType at runtime).
                }
            }
        }
    }

    /// <summary>
    ///     Checks whether <paramref name="candidateType"/> satisfies all constraints declared on
    ///     <paramref name="typeParam"/>.
    /// </summary>
    private static bool SatisfiesConstraints(INamedTypeSymbol candidateType, ITypeParameterSymbol typeParam)
    {
        // Interface / base-class constraints (e.g. where T : ICommand, ISomething).
        // Only INamedTypeSymbol constraints (interfaces and classes) are supported here.
        // Other constraint kinds — such as array types, pointer types, or type-parameter
        // constraints (where T : U) — are not representable as LiteBus message markers, so
        // returning false for them is both correct and safe.
        foreach (var constraint in typeParam.ConstraintTypes)
        {
            if (constraint is not INamedTypeSymbol namedConstraint)
                return false;

            if (!IsAssignableTo(candidateType, namedConstraint))
                return false;
        }

        // Reference-type constraint (where T : class)
        if (typeParam.HasReferenceTypeConstraint && candidateType.TypeKind == TypeKind.Struct)
            return false;

        // Value-type constraint (where T : struct)
        if (typeParam.HasValueTypeConstraint && candidateType.TypeKind != TypeKind.Struct)
            return false;

        // new() constraint
        if (typeParam.HasConstructorConstraint)
        {
            var hasDefaultCtor = candidateType.InstanceConstructors
                .Any(static c => c.Parameters.IsEmpty && c.DeclaredAccessibility == Accessibility.Public);
            if (!hasDefaultCtor && candidateType.TypeKind != TypeKind.Struct)
                return false;
        }

        return true;
    }

    /// <summary>
    ///     Returns <see langword="true"/> when <paramref name="type"/> is assignable to
    ///     <paramref name="target"/> (same type, implements the interface, or extends the class).
    /// </summary>
    private static bool IsAssignableTo(INamedTypeSymbol type, INamedTypeSymbol target)
    {
        if (SymbolEqualityComparer.Default.Equals(type, target) ||
            SymbolEqualityComparer.Default.Equals(type.OriginalDefinition, target.OriginalDefinition))
            return true;

        foreach (var iface in type.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(iface, target) ||
                SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, target.OriginalDefinition))
                return true;
        }

        var baseType = type.BaseType;
        while (baseType is not null)
        {
            if (SymbolEqualityComparer.Default.Equals(baseType, target) ||
                SymbolEqualityComparer.Default.Equals(baseType.OriginalDefinition, target.OriginalDefinition))
                return true;
            baseType = baseType.BaseType;
        }

        return false;
    }

    // -----------------------------------------------------------------------
    // Symbol helpers
    // -----------------------------------------------------------------------

    private static INamedTypeSymbol[] ResolveSymbols(Compilation compilation, string[] names)
    {
        var result = new List<INamedTypeSymbol>(names.Length);
        foreach (var name in names)
        {
            var symbol = compilation.GetTypeByMetadataName(name);
            if (symbol is not null)
                result.Add(symbol);
        }

        return result.ToArray();
    }

    private static bool ImplementsAny(INamedTypeSymbol type, INamedTypeSymbol[] markers)
    {
        if (markers.Length == 0)
            return false;

        foreach (var iface in type.AllInterfaces)
        {
            var original = iface.OriginalDefinition;
            foreach (var marker in markers)
            {
                if (SymbolEqualityComparer.Default.Equals(original, marker) ||
                    SymbolEqualityComparer.Default.Equals(iface, marker))
                    return true;
            }
        }

        return false;
    }

    private static string FullyQualifiedName(INamedTypeSymbol type)
    {
        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    // -----------------------------------------------------------------------
    // Code generation
    // -----------------------------------------------------------------------

    private static string GenerateSource(
        List<INamedTypeSymbol> commandHandlers,
        List<INamedTypeSymbol> eventHandlers,
        List<INamedTypeSymbol> queryHandlers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace LiteBus.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("///     Compile-time discovered LiteBus handler types for AOT-safe registration.");
        sb.AppendLine("///     Generated by LiteBus.SourceGenerator – do not edit manually.");
        sb.AppendLine("///     <para>");
        sb.AppendLine("///         Use the per-category properties when registering specific modules, or");
        sb.AppendLine("///         <see cref=\"All\" /> to register every discovered type at once.");
        sb.AppendLine("///     </para>");
        sb.AppendLine("///     <para>");
        sb.AppendLine("///         Open generic handlers (e.g. <c>class Validator&lt;T&gt; : ICommandPreHandler&lt;T&gt;</c>)");
        sb.AppendLine("///         are automatically closed against every matching concrete message type and included");
        sb.AppendLine("///         as <c>typeof(Validator&lt;MyCommand&gt;)</c> entries – no runtime");
        sb.AppendLine("///         <c>MakeGenericType</c> is required.");
        sb.AppendLine("///     </para>");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <example>");
        sb.AppendLine("/// <code>");
        sb.AppendLine("/// services.AddLiteBus(lb =>");
        sb.AppendLine("/// {");
        sb.AppendLine("///     lb.AddCommandModule(cmd => cmd.Register(GeneratedLiteBusHandlers.CommandHandlers));");
        sb.AppendLine("///     lb.AddEventModule(evt  => evt.Register(GeneratedLiteBusHandlers.EventHandlers));");
        sb.AppendLine("///     lb.AddQueryModule(qry  => qry.Register(GeneratedLiteBusHandlers.QueryHandlers));");
        sb.AppendLine("/// });");
        sb.AppendLine("/// </code>");
        sb.AppendLine("/// </example>");
        sb.AppendLine("public static class GeneratedLiteBusHandlers");
        sb.AppendLine("{");

        AppendTypeArray(sb, "CommandHandlers", "Compile-time discovered command handler types (including closed forms of open-generic handlers).", commandHandlers);
        sb.AppendLine();

        AppendTypeArray(sb, "EventHandlers", "Compile-time discovered event handler types (including closed forms of open-generic handlers).", eventHandlers);
        sb.AppendLine();

        AppendTypeArray(sb, "QueryHandlers", "Compile-time discovered query handler types (including closed forms of open-generic handlers).", queryHandlers);
        sb.AppendLine();

        var all = commandHandlers.Concat(eventHandlers).Concat(queryHandlers).ToList();
        AppendTypeArray(sb, "All", "All compile-time discovered LiteBus handler types (commands + events + queries).", all);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendTypeArray(
        StringBuilder sb,
        string propertyName,
        string summary,
        List<INamedTypeSymbol> types)
    {
        sb.AppendLine($"    /// <summary>{summary}</summary>");
        sb.AppendLine($"    public static IReadOnlyList<Type> {propertyName} {{ get; }} =");

        if (types.Count == 0)
        {
            sb.AppendLine("        Array.Empty<Type>();");
            return;
        }

        sb.AppendLine("        new Type[]");
        sb.AppendLine("        {");

        foreach (var type in types)
        {
            sb.AppendLine($"            typeof({FullyQualifiedName(type)}),");
        }

        sb.AppendLine("        };");
    }
}
