using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LiteBus.SourceGenerator;

/// <summary>
///     Roslyn incremental source generator that discovers all LiteBus handler types in the compilation
///     and emits an AOT-safe <c>GeneratedLiteBusHandlers</c> class. This class replaces the
///     reflection-based <c>RegisterFromAssembly</c> with a statically-known list of <c>typeof(…)</c>
///     references that survive IL trimming and Native AOT publishing.
/// </summary>
[Generator]
public sealed class LiteBusHandlersGenerator : IIncrementalGenerator
{
    // -----------------------------------------------------------------------
    // Interface full-names the generator recognises as "LiteBus handler markers"
    // -----------------------------------------------------------------------

    /// <summary>
    ///     Fully-qualified names of the three domain-specific marker interfaces.
    ///     Any concrete (non-abstract, non-interface) type that transitively implements one of
    ///     these is included in the corresponding generated collection.
    /// </summary>
    private static readonly string[] CommandMarkerNames =
    [
        "LiteBus.Commands.Abstractions.IRegistrableCommandConstruct"
    ];

    private static readonly string[] EventMarkerNames =
    [
        "LiteBus.Events.Abstractions.IRegistrableEventConstruct"
    ];

    private static readonly string[] QueryMarkerNames =
    [
        "LiteBus.Queries.Abstractions.IRegistrableQueryConstruct"
    ];

    /// <summary>
    ///     All domain markers together – used to build the combined <c>All</c> property.
    /// </summary>
    private static readonly string[] AllMarkerNames =
        [.. CommandMarkerNames, .. EventMarkerNames, .. QueryMarkerNames];

    // -----------------------------------------------------------------------
    // IIncrementalGenerator implementation
    // -----------------------------------------------------------------------

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // We need the full compilation to walk all named types, so we use
        // the compilation provider (one value per compilation) and the
        // class-declaration syntax provider together.

        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Collect();

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations);

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) =>
        {
            var (compilation, classes) = source;
            Execute(compilation, classes, spc);
        });
    }

    // -----------------------------------------------------------------------
    // Core logic
    // -----------------------------------------------------------------------

    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classes,
        SourceProductionContext context)
    {
        // Resolve the marker interface symbols.  If none resolve (e.g. the
        // LiteBus.Commands.Abstractions assembly is not referenced) we skip
        // that category silently.
        var commandMarkers = ResolveSymbols(compilation, CommandMarkerNames);
        var eventMarkers = ResolveSymbols(compilation, EventMarkerNames);
        var queryMarkers = ResolveSymbols(compilation, QueryMarkerNames);

        if (commandMarkers.Length == 0 && eventMarkers.Length == 0 && queryMarkers.Length == 0)
        {
            // Nothing to generate – LiteBus abstractions not referenced.
            // Emit an empty class so the file can be seen for debugging.
            var emptySource = "// <auto-generated/>\n// LiteBus.SourceGenerator: no LiteBus abstractions found in compilation.\n";
            context.AddSource("GeneratedLiteBusHandlers.g.cs", SourceText.From(emptySource, Encoding.UTF8));
            return;
        }

        var commandHandlers = new List<INamedTypeSymbol>();
        var eventHandlers = new List<INamedTypeSymbol>();
        var queryHandlers = new List<INamedTypeSymbol>();

        foreach (var classDecl in classes)
        {
            var semanticModel = compilation.GetSemanticModel(classDecl.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol typeSymbol)
                continue;

            if (!IsConcreteType(typeSymbol))
                continue;

            if (ImplementsAny(typeSymbol, commandMarkers))
                commandHandlers.Add(typeSymbol);
            else if (ImplementsAny(typeSymbol, eventMarkers))
                eventHandlers.Add(typeSymbol);
            else if (ImplementsAny(typeSymbol, queryMarkers))
                queryHandlers.Add(typeSymbol);
        }

        var source = GenerateSource(commandHandlers, eventHandlers, queryHandlers);
        context.AddSource("GeneratedLiteBusHandlers.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private static INamedTypeSymbol[] ResolveSymbols(Compilation compilation, string[] names)
    {
        var result = new List<INamedTypeSymbol>(names.Length);
        foreach (var name in names)
        {
            var symbol = compilation.GetTypeByMetadataName(name);
            if (symbol is not null)
                result.Add(symbol);
        }

        return result.ToArray();
    }

    private static bool IsConcreteType(INamedTypeSymbol type)
    {
        // Exclude interfaces and abstract classes.
        // Allow closed generic types (e.g. MyHandler<string>) but exclude
        // unbound / open generic type definitions (e.g. MyHandler<>).
        return type.TypeKind == TypeKind.Class
               && !type.IsAbstract
               && !type.IsUnboundGenericType;
    }

    private static bool ImplementsAny(INamedTypeSymbol type, INamedTypeSymbol[] markers)
    {
        if (markers.Length == 0)
            return false;

        foreach (var iface in type.AllInterfaces)
        {
            var original = iface.OriginalDefinition;
            foreach (var marker in markers)
            {
                if (SymbolEqualityComparer.Default.Equals(original, marker) ||
                    SymbolEqualityComparer.Default.Equals(iface, marker))
                    return true;
            }
        }

        return false;
    }

    private static string FullyQualifiedName(INamedTypeSymbol type)
    {
        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    // -----------------------------------------------------------------------
    // Code generation
    // -----------------------------------------------------------------------

    private static string GenerateSource(
        List<INamedTypeSymbol> commandHandlers,
        List<INamedTypeSymbol> eventHandlers,
        List<INamedTypeSymbol> queryHandlers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace LiteBus.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("///     Compile-time discovered LiteBus handler types for AOT-safe registration.");
        sb.AppendLine("///     Generated by LiteBus.SourceGenerator – do not edit manually.");
        sb.AppendLine("///     <para>");
        sb.AppendLine("///         Use the per-category properties when registering specific modules, or");
        sb.AppendLine("///         <see cref=\"All\" /> to register every discovered type at once.");
        sb.AppendLine("///     </para>");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <example>");
        sb.AppendLine("/// <code>");
        sb.AppendLine("/// services.AddLiteBus(lb =>");
        sb.AppendLine("/// {");
        sb.AppendLine("///     lb.AddCommandModule(cmd => cmd.Register(GeneratedLiteBusHandlers.CommandHandlers));");
        sb.AppendLine("///     lb.AddEventModule(evt  => evt.Register(GeneratedLiteBusHandlers.EventHandlers));");
        sb.AppendLine("///     lb.AddQueryModule(qry  => qry.Register(GeneratedLiteBusHandlers.QueryHandlers));");
        sb.AppendLine("/// });");
        sb.AppendLine("/// </code>");
        sb.AppendLine("/// </example>");
        sb.AppendLine("public static class GeneratedLiteBusHandlers");
        sb.AppendLine("{");

        // CommandHandlers
        AppendTypeArray(sb, "CommandHandlers", "Compile-time discovered command handler types.", commandHandlers);
        sb.AppendLine();

        // EventHandlers
        AppendTypeArray(sb, "EventHandlers", "Compile-time discovered event handler types.", eventHandlers);
        sb.AppendLine();

        // QueryHandlers
        AppendTypeArray(sb, "QueryHandlers", "Compile-time discovered query handler types.", queryHandlers);
        sb.AppendLine();

        // All – union of the three
        var all = commandHandlers
            .Concat(eventHandlers)
            .Concat(queryHandlers)
            .ToList();
        AppendTypeArray(sb, "All", "All compile-time discovered LiteBus handler types (commands + events + queries).", all);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendTypeArray(
        StringBuilder sb,
        string propertyName,
        string summary,
        List<INamedTypeSymbol> types)
    {
        sb.AppendLine($"    /// <summary>{summary}</summary>");
        sb.AppendLine($"    public static IReadOnlyList<Type> {propertyName} {{ get; }} =");

        if (types.Count == 0)
        {
            sb.AppendLine("        Array.Empty<Type>();");
            return;
        }

        sb.AppendLine("        new Type[]");
        sb.AppendLine("        {");

        foreach (var type in types)
        {
            sb.AppendLine($"            typeof({FullyQualifiedName(type)}),");
        }

        sb.AppendLine("        };");
    }
}
